### PR TITLE
Fix Git version and Remove old Platform on emucore.vcxproj

### PR DESCRIPTION
**Pull request by Zangetsu38**
Rpcs3 So now displays the git revision number, I also remove all win32 platform emucore that are useless now.

### CODE REVIEW

**Comment by Bigpet** [comment]
it's `_WIN32` not `WIN32`. Also what exactly is the purpose of the `#ifndef __unix__` if you are testing against `_WIN32` the rest of the time you should test against it there. So presumably `#ifdef _WIN32`

**Comment by Bigpet** [comment]
it's seems like it would be a lot better to not remove the default `git-version.h` and instead just change the line `#define RPCS3_GIT_VERSION_NO_UPDATE 1 ` to `#define RPCS3_GIT_VERSION_NO_UPDATE 0 `

Then you don't need the `#if` around the include anymore either

**Comment by Zangetsu38** [comment]
@Bigpet  I did not understand your first message, but if it's even really hollowing, git-version.h shall in no case left the project, (If there is a project file which turns red "Modified" and it c is not good) it is created using Visual Studio or so Cmake (Something I should look for that later), and the WIN32 in places _WIN32 I'll busy myself, it's absolutely okay that .

**Comment by Bigpet** [comment]
alright, I made a pull-request to you with the cmake script and eliminated the now useless ifs

**Comment by Zangetsu38** [comment]
Oh, Yes THX 
I was going to do but good, you my saves time :)

**Comment by Bigpet** [comment]
my bad, forgot to remove a semicolon

**Pull request merged**
