### PR TITLE
Test mode, RSXIO changes reverted and experimental DMA implementation

### PR DESCRIPTION
**Pull request by tambry**

### CODE REVIEW

**Comment by AlexAltea** [comment]
Considering how RSX is emulated on RPCS3, *your* DMA implementation won't work.

PS: Just a kind reminder while copying files: http://www.gnu.org/licenses/gpl-2.0.html ;-)

**Comment by O1L** [comment]
Another unnecessary option in "Settings"? Just made rigth implementation of RSX DMA. And remove this option from GUI, please.

**Comment by Ekaseo** [comment]
is there still something wrong with this when its not getting merged?

**Comment by AlexAltea** [comment]
@Ekaseo: Right now there is a merge conflict due to a previous pull. Rebasing is required.

**Comment by Ekaseo** [comment]
is this still not finished?

**Comment by tambry** [comment]
@Ekaseo This one is ready for merge. Though DMA doesn't work properly, yet. Also seems like another PR created conflicts with this one.

**Comment by Hykem** [comment]
@tambry If you can, please fix the recent conflicts that were introduced by the last PR. Otherwise I'll have to merge this manually. Thanks!

**Pull request merged**
