### PR TITLE
Migration to WIN64

### PR DESCRIPTION
**Pull request by Zangetsu38**
Given that rpcs3 exclusively on Windows x64, it is totally entitled to still have the indication for a 32-bit system.

### CODE REVIEW

**Comment by Bigpet** [comment]
There is no good reason to do this

**Comment by Zangetsu38** [comment]
@Bigpet  If rpcs3 is no longer 32 bit, so keep that in WIN32 is meaningless.

**Comment by Bigpet** [comment]
The documentation clearly says

>_WIN32
>Defined for applications for Win32 and Win64. Always defined.

Most of those `#ifs` do just depend on the "Win32 API" (nothing to do with bitness, it's just the name of the API) so changing it just to change it is not a good reason.

Especially since you are changing among other things header of external libraries like OpenAL, which would make merging future updates hard for no reason.

**Comment by Zangetsu38** [comment]
There are no problems, and for me WIN32 for Windows X86 and X64 and WIN64 Exclusively for Windows x64.
So for me, it just makes sense to spend the code WIN64 when the 32-bit version no longer exists.

**Comment by Bigpet** [comment]
Again, if we update simpleini or openal then this can cause merge conflicts. This is just change for the sake of change. When you say "There are no problems" then I can say the same. There are no problems with keeping it as it is.

**Comment by Zangetsu38** [comment]
I do not understand it to merge conflict talk to you?

**Comment by tambry** [comment]
I see it being OK if it's in RPCS3 only - meaning no changes to SimpleINI, OpenAL, etc.
But ultimately there really is no effect.

**Comment by Zangetsu38** [comment]
For OpenAL and SimpleINI, I did not think it could cause problems.
According to OpenAL Soft, he appeared to be updated very rarely (The last update for 2013 anyway), so in the end it's not a problem.
And if there is an updated, just put it in place of the WIN64 WIN32 is quick and easy.

**Comment by Bigpet** [comment]
So your goal is to make parts of the code be only compilable on the most narrow definition of what we currently support ?

Then why don't you just change it all to `#if _MSC_VER >=1800` since we only support Visual Studio versions after 2013?

**Comment by Zangetsu38** [comment]
Because it is not the same, only to WIN64 enough I think ^^

**Comment by Bigpet** [comment]
Oh, but why is it enough?

**Comment by Zangetsu38** [comment]
It just removes any annotations in Windows 32 that's it, no need to put something else.
For the version of Visual Studio is the LNS decides.
And will soon go into VS 2105

**Comment by Bigpet** [comment]
Oh, but the #if _MSC_VER only increases with version. So if you check for `>=1800` it compiles for all versions after and include VS 2013, including VS 2015 and everything after it.

It just removes any annotations that we support VS < 2013

**Comment by Zangetsu38** [comment]
I have not understood everything, I just wanted to remove the WIN32 na more places to be is all ^^

**Comment by Bigpet** [comment]
You are unnecessarily constraining preprocessor checks, this doesn't fix anything, this doesn't make the code more clear in its intend, this doesn't prevent any possible mistakes, this does not help in any way. Not to mention, you are changing external code for no reason.

**Comment by Zangetsu38** [comment]
The external code?

**Comment by Bigpet** [comment]
The OpenAL and SimpleIni headers are external code since we did not write them.

**Comment by Zangetsu38** [comment]
hmm I see so I should revert to these two?

**Comment by Bigpet** [comment]
This still gives no good reason to change the rest

**Comment by Zangetsu38** [comment]
If, for me it just makes sense, WIN32 has nothing to do it now, that's all, it's just cleaning machines

**Comment by Bigpet** [comment]
I've made my opinion clear and I've given you the official definition of the macro.

There is just as much reason to add a check for `_MSC_VER >=1800`. None

You're gonna have to keep a "WIN32" in there anyway because "_WIN64_WINNT" is not a thing 

look into the sourcecode of "xaudio2.h" it checks `#if(_WIN32_WINNT < _WIN32_WINNT_WIN8)` 

You want to change the windows SDK header too now?

**Comment by Zangetsu38** [comment]
I looked, I do not think it is a problem.
It comes to the same, except that ca eliminates Windows 32 that's all.
But why I will change the Windows SDK?

**Comment by Bigpet** [comment]
Look at the version in the Windows 8.1 kit

Also search through all the windows sdk headers for `_WIN64_WINNT` and `_WIN32_WINNT`

**Comment by O1L** [comment]
Sorry, but this is a stupid and useless PR. Don't merge this, please.

**Comment by Alegend45** [comment]
Agreed.

**Comment by Zangetsu38** [comment]
What? it is anything but stupid, it just seems obvious to me.

**Comment by O1L** [comment]
You just don't understand, what it means the _WIN32 macro.
Bigpet had already explained everything.

**Comment by Zangetsu38** [comment]
If I understood.
WIN32 macro is for both, Windows 32-bit and 64-bit Windows.
And the WIN64 macro was exclusively a Windows 64 Bit.
Microsoft explains it well, it takes WIN64 used when the program is intended to be only on 64-bit Windows.
So there is absolutely no problem with what I did, in the sense that there is more than 32-bit RPCS3.
So that my paraissais totally illogical to leave WIN32 while rpcs3 was only 64 bits, that's all.

**Comment by Bigpet** [comment]
> it takes WIN64 used when the program

No, it takes WIN64 when used to guard code that is specific to only WIN64, most of the ones you replaced guarded code that is not specific to WIN64. There is no reason to think of the code at the level of "whole project" in this case.

Not to mention, you still didn't explain the usage of `_WIN64_WINNT`

**Comment by Zangetsu38** [comment]
I take this off.

**Comment by O1L** [comment]
I don't agree with these changes anyway. This is senseless.

**Comment by Bigpet** [comment]
You keep saying "no problem" but yet you still changed the cotire script without being aware of the effects. I keep bringing up this nitpicks to drive home that there are problems and you don't understand them.

So keeping it as is is actually no problem while your "no problem" is just "no problem that I can see" which is not reliable as we've established multiple times now.

**Comment by Hykem** [comment]
Sorry but this is completely pointless and unnecessary. I'm closing this one.

**Comment by Zangetsu38** [comment]
I really do not understand or is the problem.
Rpcs3 exclusively 64-bit version, so why stay with macro WIN32 is totally illogical.
Even Microsoft say that for a program developed exclusively in 64-bit must be set WIN64.
So where is the problem in the sense that I did just makes sense and of course makes sense, in the sense rpcs3 exclusively on WIN64.
The WIN32 is just information from the past, the past is the presence of a 32-bit rpcs3, and it will bring to disappear together with 32-bit Windows.

**Comment by paulsapps** [comment]
See here: http://stackoverflow.com/questions/6679396/should-i-define-both-win32-and-win64-in-64bit-build

you should ONLY use win64 define for conditional compilation of stuff that only goes into the 64bit windows build, everything else should use win32 even if you only target 64bit windows, its how the SDK headers work

**Comment by Bigpet** [comment]
You may also be confusing the `WIN32` in the project defines and the build-in `_WIN32` those are not  the same

**Comment by Zangetsu38** [comment]
I understand nothing of why Microsoft says that then:
_WIN32=Defined for applications for Win32 and Win64. Always defined.

_WIN64=Defined for applications for Win64.

I may be confusing two different thing.
But the site that explains the C ++ clearly say What must use _WIN64 or WIN64 for 64-bit application.
So yes, I'm lost.

**Comment by Bigpet** [comment]
And is the code inside the `#if WIN64` that you set specific to Win64?

**Comment by Zangetsu38** [comment]
But I not understand the code is necessarily specific for WIN64.
In the sense that there are no Windows 32 release.
So although initially the code can be running Windows 32, the program will be on WIN64.

**Comment by Bigpet** [comment]
As I already explained to you it's also specific to Visual Studio versions after 2013 but we  don't test for that either

**Comment by Zangetsu38** [comment]
I see,I guess I need to learn more to understand.

**Pull request closed without merging**
