### PR TITLE
About ppu thread stacksize

### PR DESCRIPTION
**Pull request by Syphurith**
I saw someone experience the issue of Assertion failed at `m_stack_size` in PPUThread.cpp which may be caused by the initial stack size or even the implementation of `sys_ppu_thread_create`. So i made it to round the requested size up to product of 4KB, even it was told to allocate 0B.
For the detailed issue and a test LLVM build of it, see [Here](http://www.emunewz.net/forum/showthread.php?tid=167481&pid=219885#pid219885). Hope this can solve the stack size problem.
*Note: If you want to test something, please take the file in the post and get the test.*

### CODE REVIEW

**Comment by tambry** [comment]
@Syphurith One game that seems to crash with that assertion is Bit Trip Runner 2: Future Legend of Rythm Alien. (It worked fine before)

Also @B1ackDaemon ran your test sample:
http://pastie.org/private/z6nozedhuher4nnor8xoea

**Comment by Syphurith** [comment]
Thanks i see the result. so the lowest allocation unit maybe 0x4000 not 0x1000(4096) indeed. I would change that after checked out the newest version.

**Comment by tambry** [comment]
@Syphurith I already made a commit on my fork that fixes it.

**Comment by Syphurith** [comment]
Thanks, you made a step. BTW. Would you want to create a macro for the allocation unit? I tried to find a file to define it within - failed. I highly doubt the "PTHREAD_STACK_MIN" is 0x4000 for higher FW. @B1ackDaemon his console is not FW4.00, so i don't know if that is really 0x1000 for some consoles.

**Comment by tambry** [comment]
@Syphurith I remember that documentation says that the max is 0x4000. Don't remember what FW docs though.

**Pull request merged**
